[package]
name = "tinyrenderer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
glam = "0.24.1"
rand = "0.8.5"
wavefront = "0.2.3"

[dependencies.image]
version = "0.24"
default-features = false
features = ["jpeg", "tga"]
